apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:80
    basicAuth: false
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
